In [12]:
import numpy as np
z=np.zeros(10)

In [13]:
z.shape=(2,5)

In [14]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
q=np.ones(2)

In [17]:
q

array([1., 1.])

In [20]:
w=np.linspace(10,20,10)

In [22]:
w.shape=(2,5)

In [23]:
w

array([[10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444],
       [15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ]])

In [24]:
z=np.linspace(2,4,5)

In [25]:
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [28]:
k=np.array([0,2,3])
k

array([0, 2, 3])

In [29]:
z[k]

array([2. , 3. , 3.5])

In [39]:
A=np.array((1,2,3,4,4,5,5,6,7,7,8,9))
B=np.array((9,8,7,6,5,4,3,2,1,2,3,4))
B.shape=(3,4)
A.shape=(4,3)
A@B

array([[ 22,  22,  22,  22],
       [ 61,  58,  55,  52],
       [ 82,  78,  74,  70],
       [112, 106, 100,  94]])

In [40]:
y = np.random.binomial(10, 0.5, size=1000)

In [41]:
y


array([ 4,  4,  7,  5,  4,  6,  2,  4,  6,  1,  2,  5,  6,  5,  4,  7,  7,
        8,  5,  4,  7,  3,  6,  7,  4,  4,  3,  7,  5,  5,  5,  5,  7,  5,
        7,  6,  5,  5,  4,  4,  7,  3,  7,  4,  4,  7,  4,  4,  6,  5,  6,
        4,  6,  6,  2,  4,  3,  6,  7,  5,  4,  6,  7,  4,  7,  4,  3,  5,
        8,  4,  7,  5,  7,  3,  5,  4,  8,  4,  5,  4,  1,  7,  3,  6,  5,
        3,  6,  5,  4,  4,  4,  4,  4,  4,  2,  5,  6,  8,  5,  3,  4,  2,
        5,  6,  7,  8,  6,  7, 10,  5,  2,  2,  6,  4,  3,  6,  4,  6,  7,
        4,  5,  4,  5,  8,  4,  8,  5,  7,  3,  6,  7,  3,  5,  7,  6,  3,
        2,  8,  4,  4,  7,  5,  1,  8,  4,  6,  3,  7,  3,  3,  8,  6,  1,
        5,  4,  5,  7,  4,  4,  3,  3,  6,  5,  3,  8,  3,  4,  5,  3,  9,
        6,  4,  7,  8,  6,  4,  8,  5,  2,  4,  4,  5,  7,  5,  4,  2,  8,
        6,  5,  5,  6,  5,  3,  5,  1,  7,  4,  5,  4,  5,  3,  7,  4,  2,
        2,  3,  7,  7,  6,  4,  5,  7,  4,  5,  5,  6,  7,  6,  8,  5,  5,
        3,  6,  4,  6,  3

In [43]:
y.mean()

4.961

In [46]:
#EX1
'''a=np.array((2,3,1,3,12,3,1,23,123,1,3,1))
x=2
def f(x,coeff):
    z=sum(x**i*coeff[i]for i in range(len(a)))
    return (z)
f(x,a)'''#not 

40452

In [54]:
def f(x,coeff):
    X=np.empty(len(coeff))
    X[0]=1
    X[1:]=x
    y=np.cumprod(X)
    return coeff@y
    

In [55]:

f(4,[1,2,3,4,4,5,6])

31033.0

In [58]:
z=np.ones(5)*2
y=np.cumprod(z)
y

array([ 2.,  4.,  8., 16., 32.])

# прихотливая индексация
x= np.arange(10)
i=np.array([2,1,3,5])

In [69]:
x[i]=22
x

array([ 0, 22, 22, 22,  4, 22,  6,  7,  8,  9])

In [73]:
np.add.at(x,i+1,1)

In [74]:
x

array([ 0, 23, 24, 24,  5, 23,  7,  7,  8,  9])

In [94]:
#разбиение на интервалы
import mathplotlib.pyplot as plt
np.random.seed(42)
x=np.random.randn(100)

b=np.linspace(-5,5,20)
c=np.zeros_like(b)
i=np.searchsorted(b,x)
np.add.at(c,i,1)

ModuleNotFoundError: No module named 'mathplotlib'

In [91]:
plt,plot(b,c)

NameError: name 'plt' is not defined