In [12]:
import numpy as np
z=np.zeros(10)

In [13]:
z.shape=(2,5)

In [14]:
z

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [16]:
q=np.ones(2)

In [17]:
q

array([1., 1.])

In [20]:
w=np.linspace(10,20,10)

In [22]:
w.shape=(2,5)

In [23]:
w

array([[10.        , 11.11111111, 12.22222222, 13.33333333, 14.44444444],
       [15.55555556, 16.66666667, 17.77777778, 18.88888889, 20.        ]])

In [24]:
z=np.linspace(2,4,5)

In [25]:
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [28]:
k=np.array([0,2,3])
k

array([0, 2, 3])

In [29]:
z[k]

array([2. , 3. , 3.5])

In [39]:
A=np.array((1,2,3,4,4,5,5,6,7,7,8,9))
B=np.array((9,8,7,6,5,4,3,2,1,2,3,4))
B.shape=(3,4)
A.shape=(4,3)
A@B

array([[ 22,  22,  22,  22],
       [ 61,  58,  55,  52],
       [ 82,  78,  74,  70],
       [112, 106, 100,  94]])